### ISSUE TITLE
Taming polyfills & web components across major browsers

### ISSUE THREAD

**Issue by drewwills** [Jasig/uPortal#1381]
Folks,

We have put a tremendous effort into introducing Web Components as a new standard for content objects in the portal.  As expected, there has been a bit of a "learning curve" in this change.

But the time has come where we need to get a firm handle on what we doing.  We need to be able to deliver working components -- reliably -- across supported browsers;  and we need, furthermore, a component we deliver today still to function properly & look attractive 6, 9, 12 months down the road.  (Spoiler:  we're not there yet.)

## Screenshots

Here are some screen captures of the current header content in `uPortal-start/data/quickstart` across 4 major browsers.  None of them is 100% functional.

### Chrome

![chrome](https://user-images.githubusercontent.com/1127174/47520780-fafc9380-d845-11e8-8a3a-d24e45a3a259.png)

### Firefox

![firefox](https://user-images.githubusercontent.com/1127174/47520785-00f27480-d846-11e8-850c-4f53ee403870.png)

### Edge

![edge](https://user-images.githubusercontent.com/1127174/47520789-064fbf00-d846-11e8-8064-6fba4ef52575.png)

### IE 11

![ie](https://user-images.githubusercontent.com/1127174/47520802-0fd92700-d846-11e8-96c9-0d92717c1ac3.png)

## A Good Plan, and Consensus

The most recent plan I am aware of is that (1) uPortal will include polyfills sufficient to take any browser to ES6 support, and (2) uPortal Ecosystem Web Components must "take it from there" if they need further polyfills, CSS applied, etc.

@ChristianMurphy @jgribonvald @cousquer @bjagg @jonathanmtran @leighgordy

Is this a good plan?

Can someone explain what I'm seeing in these screenshots?  (I can make some time to pitch in with fixing.)

**Comment by leighgordy** [comment]
Sorry for the late reply, I don't get notified from GitHub anymore, for some odd reason!

I know I have been highly skeptical of web components in the past but with Firefox supporting them and IE currently developing support, I am no longer a skeptic and I can see the value in your approach. 

In regards to the plan. We are not developing web components locally as yet but our approach is exactly the same as yours for our AMD modules. We have to transpile to ES5 and use pollyfills to support legacy browsers. You should not think that complexity as a cost of web components, its just how JavaScript projects are built these days. 

We have not built any React web components as yet because React events and web components don't mix very well. [React Fire](https://github.com/facebook/react/issues/13525) promises to fix event handling which means React should hopefully work properly web components in a few months.

I think your plan is a good one!

**Comment by cousquer** [comment]
Heya Drew,

Have a look at https://github.com/cousquer/CardWebComponents , See it in
action: https://cousquer.github.io/CardWebComponents/
For the moment it's a Proof of concept, there is still an issue, Many
Thanks to Christian Murphy for the insights.😉
But This Web Component is i18n in en-US, es-ES, fr-FR, nl-NL, meets AA
level in WCAG 2.1 (yes the new one!)...
would be happy if in the future to push it in uPortal-contrib

-Christian



Le ven. 2 nov. 2018 à 19:39, Leigh Gordon <notifications@github.com> a
écrit :

**Comment by ChristianMurphy** [comment]
These changes have been applied in uPortal [5.3.0](https://github.com/Jasig/uPortal/releases/tag/v5.3.0) and continued to be enhanced in continued releases.
